# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: PR
on:
 pull_request_target:
   types: [opened, synchronize, reopened, ready_for_review]
   
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: mshick/add-pr-comment@v1
      with:
        message: |
          Simple PR
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
        allow-repeats: false # This is the default
    # - name: Slash Command Dispatch
    #   uses: peter-evans/slash-command-dispatch@v2
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     commands: |
    #       commands