name: PR target merge
on:
 pull_request_target:
   types: [opened, synchronize, reopened, ready_for_review]
   
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.1"
        env:
          GITHUB_TOKEN: "${{ secrets.MERGE }}"
          MERGE_LABELS: "Triage,!work in progress"
          MERGE_REMOVE_LABELS: "Triage"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_FORKS: "true"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "rebase"
